#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
autoload -Uz promptinit
promptinit
prompt cloud


# zsh options
setopt \
    append_history	\
    auto_cd		\
    auto_list		\
    bang_hist		\
    clobber		\
    correct		\
    extended_history	\
    noextendedglob	\
    glob		\
    glob_complete	\
    hist_ignore_space	\
    hist_no_functions	\
    hist_no_store	\
    hist_reduce_blanks	\
    hist_save_no_dups	\
    nohistverify	\
    list_packed		\
    long_list_jobs	\
    mark_dirs		\
    nobeep		\
    nonomatch		\
    notify		\
    prompt_subst	\
    nohup

unsetopt share_history

if [[ -x =vim ]]; then
    alias vi='vim'
    export EDITOR=vim
else
    export EDITOR=vi
fi

test -e ${HOME}/.iterm2_shell_integration.zsh && source ${HOME}/.iterm2_shell_integration.zsh

alias	.="source"
alias	j	"jobs"
alias   bsdbook="setenv CVSROOT :ext:chez.mckusick.com:/home/staff/mckusick/book/cvs;setenv CVS_RSH ssh"
alias   p4bsd="setenv P4PORT perforce.freebsd.org:1666"
alias	zoo="ssh zoo.freebsd.org"
alias	zoomacs="ssh -f zoo.freebsd.org emacs -l .emacs-login"
alias	freefall="ssh freefall.freebsd.org"
alias   sobu "ssh sobu.neville-neil.com"
alias   freeirc="slogin -L6667:irc.efnet.net:6667 gnn@sobu.neville-neil.com"
alias   power="ipmitool -I lanplus -H \!^ -U hrt -P hrt chassis power cycle"
alias	ipmi-serial="ipmitool -I lanplus -H \!^\-ipmi -U hrt -P hrt sol activate"
alias	sourceforge="ssh shell.sourceforge.net"
alias	punkwifi="sudo wpa_supplicant -Dbsd -iwlan0 -c /etc/wpa_supplicant.conf"

# zoo only
export MAKEOBJDIR=/tank/users/gnn/obj
